name: "Get AZ CLI version"
description: "Get AZ CLI version and save with environment variable"
inputs:
  url:
    description: "URL to the configuration file of external dependencies."
    required: false
    default: https://raw.githubusercontent.com/Azure/azure-javaee-iaas/main/external-deps-versions.properties
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -Lo external-deps-versions.properties ${{ inputs.url }}
        source external-deps-versions.properties
        echo "azCliVersion=${AZ_CLI_VERSION}" >> $GITHUB_ENV
