name: Merge upstream branches for WLS on AKS
on:
  workflow_dispatch:
  # Sample cURL
  # curl --verbose -X POST https://api.github.com/repos/<github_user>/weblogic-azure/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -H 'Authorization: token <personal_access_token>' --data '{"event_type": "aks-upstream-sync"}'
  repository_dispatch:
    types: [aks-upstream-sync]
env:
  userName: ${{ secrets.USER_NAME }}
  userEmail: ${{ secrets.USER_EMAIL }}
  gitToken: ${{ secrets.GIT_TOKEN }}
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.gitToken }}
      - name: Merge upstream
        run: |
          git config --global user.name ${{ env.userName }}
          git config --global user.email ${{ env.userEmail }}

          # "git checkout main" is unnecessary, already here by default
          git pull --unshallow

          git remote add upstream https://github.com/oracle/weblogic-azure.git
          git fetch upstream

          git merge --no-edit upstream/main
          git push origin main
