name: Test WLS on AKS without dependency creation

on:
  workflow_dispatch:
    inputs:
      gitUserNameForArtifactsLocation:
        description: 'Replaced into https://raw.githubusercontent.com/#gitUserName#/weblogic-azure/#testbranchName#/weblogic-azure-aks/src/main/arm/'
        required: true
        default: oracle
      testBranchNameForArtifactsLocation:
        description: 'Replaced into https://raw.githubusercontent.com/#gitUserName#/weblogic-azure/#testbranchName#/weblogic-azure-aks/src/main/arm/'
        required: true
        default: main
  # sample cURL
  # curl --verbose -X POST https://api.github.com/repos/<github_user>/weblogic-azure/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -H 'Authorization: token <personal_access_token>' --data '<request_data>'
  # sample <request_data>
  # {"event_type": "aks-integration-test-without-dependency-creation", "client_payload": {"isForDemo": "false", "disambiguationSuffix": "1397121054", "storageAccountName": "wlsdsa13971210545", "storageContainerName": "wlsdcon13971210545", "dbName": "wlsdb13971210545"}}
  # the request data can be get from setupWlsAksDependency pipeline, please checkout the summary page and download the generated artifact name 'integration-test-data'
  repository_dispatch:
    types: [aks-integration-test-without-dependency-creation]

env:
    refJavaee: 1a21a792d6bae6768b155945cf2703c3026ac691
    azCliVersion: 2.29.0
    azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
    location: eastus
    resourceGroupForWlsAks: wlsd-aks-${{ github.event.client_payload.disambiguationSuffix }}-${{ github.run_number }}
    dbAdminUser: weblogic
    dbPassword: ${{ secrets.DB_PASSWORD }}
    dbName: ${{ github.event.client_payload.dbName }}
    servicePrincipal: ${{ secrets.SERVICE_PRINCIPAL }}
    ocrSSOPSW: ${{ secrets.ORC_SSOPSW }}
    ocrSSOUser: ${{ secrets.ORC_SSOUSER }}
    wdtRuntimePassword: ${{ secrets.WDT_RUNTIMEPSW}}
    wlsUserName: ${{ secrets.WLS_USERNAME }}
    wlsPassword: ${{ secrets.WLS_PSW }}
    userAssignedManagedIdentity: ${{ secrets.USER_ASSIGNED_MANAGED_IDENTITY_ID }}
    storageAccountName: ${{ github.event.client_payload.storageAccountName }}
    storageContainerName: ${{ github.event.client_payload.storageContainerName }}
    isForDemo: ${{ github.event.client_payload.isForDemo }}

jobs:
    preflight:
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Set up bicep
              run: |
                curl -Lo bicep https://github.com/Azure/bicep/releases/download/v0.4.613/bicep-linux-x64
                chmod +x ./bicep
                sudo mv ./bicep /usr/local/bin/bicep
                bicep --version
            - name: Checkout azure-javaee-iaas
              uses: actions/checkout@v2
              with:
                repository: Azure/azure-javaee-iaas
                path: azure-javaee-iaas
                ref: ${{ env.refJavaee }}
            - name: Build azure-javaee-iaas
              run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
            - name: Checkout weblogic-azure
              uses: actions/checkout@v2
              with:
                path: weblogic-azure
            - name: Build and test weblogic-azure/weblogic-azure-aks
              run: mvn -Pbicep -Ddev -Passembly clean install --file weblogic-azure/weblogic-azure-aks/pom.xml
            - name: Generate artifact file name and path
              id: artifact_file
              run: |
                version=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' weblogic-azure/weblogic-azure-aks/pom.xml)
                artifactName=wls-on-aks-azure-marketplace-$version-arm-assembly
                unzip weblogic-azure/weblogic-azure-aks/target/$artifactName.zip -d weblogic-azure/weblogic-azure-aks/target/$artifactName
                echo "##[set-output name=artifactName;]${artifactName}"
                echo "##[set-output name=artifactPath;]weblogic-azure/weblogic-azure-aks/target/$artifactName"
            - name: Archive weblogic-azure/weblogic-azure-aks template
              uses: actions/upload-artifact@v1
              if: success()
              with:
                name: ${{steps.artifact_file.outputs.artifactName}}
                path: ${{steps.artifact_file.outputs.artifactPath}}
            - name: Checkout Azure-Samples/cargotracker-azure
              uses: actions/checkout@v2
              with:
                repository: Azure-Samples/cargotracker-azure
                path: cargotracker
            - name: Maven build web app
              run: |
                mvn clean install -PweblogicOnAks --file cargotracker/pom.xml
            - uses: azure/login@v1
              id: azure-login
              with:
                creds: ${{ env.azureCredentials }}
            - name: Upload built web app war file
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    az storage blob upload --account-name ${{ env.storageAccountName }} --container-name ${{ env.storageContainerName }} --file cargotracker/target/cargo-tracker.war --name cargo-tracker.war  
    deploy-wls-on-aks:
        needs: preflight
        runs-on: ubuntu-latest
        steps:
            - name: Checkout weblogic-azure
              uses: actions/checkout@v2
              with:
                path: weblogic-azure
            - name: Get version information from weblogic-azure/weblogic-azure-aks/pom.xml
              id: version
              run: |
                version=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' weblogic-azure/weblogic-azure-aks/pom.xml)
                echo "version=${version}" >> $GITHUB_ENV
            - name: Output artifact name for Download action
              id: artifact_file
              run: |
                artifactName=wls-on-aks-azure-marketplace-$version-arm-assembly
                echo "artifactName=${artifactName}" >> $GITHUB_ENV
                echo "##[set-output name=artifactName;]${artifactName}"
            - name: Download artifact for deployment
              uses: actions/download-artifact@v1
              with:
                name: ${{steps.artifact_file.outputs.artifactName}}
            - uses: azure/login@v1
              id: azure-login
              with:
                creds: ${{ env.azureCredentials }}
            - name: Query web app blob url and set to env
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    cargoTrackerBlobUrl=$(az storage blob url --account-name ${{ env.storageAccountName }} --container-name ${{ env.storageContainerName }} --name cargo-tracker.war -o tsv)
                    polishedUrl=$(echo ${cargoTrackerBlobUrl} | sed 's,/,\\\/,g')
                    echo "cargoTrackerBlobUrl=${polishedUrl}" >> $GITHUB_ENV
            - name: Create Resource Group
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    echo "create resource group" ${{ env.resourceGroupForWlsAks }}
                    az group create --verbose --name ${{ env.resourceGroupForWlsAks }} --location ${{ env.location }}
            - name: Checkout Azure-Samples/cargotracker-azure
              uses: actions/checkout@v2
              with:
                repository: Azure-Samples/cargotracker-azure
                path: cargotracker
            - name: Prepare parameter file
              run: |
                echo "replace placeholders using real parameter"
                sed -i "s/#location#/${location}/g; \
                        s/#wlsUserName#/${wlsUserName}/g; \
                        s/#wlsPassword#/${wlsPassword}/g; \
                        s/#userAssignedManagedIdentity#/${userAssignedManagedIdentity}/g; \
                        s/#ocrSSOPSW#/${ocrSSOPSW}/g; \
                        s/#ocrSSOUser#/${ocrSSOUser}/g; \
                        s/#appPackageUrls#/${cargoTrackerBlobUrl}/g; \
                        s/#servicePrincipal#/${servicePrincipal}/g; \
                        s/#wdtRuntimePassword#/${wdtRuntimePassword}/g; \
                        s/#testbranchName#/${{ github.event.inputs.testBranchNameForArtifactsLocation }}/g; \
                        s/#gitUserName#/${{ github.event.inputs.gitUserNameForArtifactsLocation }}/g; \
                        s/#dbPassword#/${dbPassword}/g; \
                        s/#dbUser#/${dbAdminUser}@${dbName}/g; \
                        s/#dsConnectionURL#/jdbc:postgresql:\/\/${dbName}.postgres.database.azure.com:5432\/postgres/g" \
                        weblogic-azure/weblogic-azure-aks/src/test/setupWlsAksParameters.json
            - name: Deploy WebLogic Server Cluster Domain offer
              id: deploy-wls-cluster
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    az deployment group create \
                    --verbose \
                    --resource-group ${{ env.resourceGroupForWlsAks }} \
                    --name wls-on-aks \
                    --parameters @weblogic-azure/weblogic-azure-aks/src/test/setupWlsAksParameters.json \
                    --template-file ${artifactName}/mainTemplate.json
            - name: Query Application Gateway URL
              run: |
                appgatewayname=$(az resource list --resource-group ${{ env.resourceGroupForWlsAks }} --query "[?type=='Microsoft.Network/applicationGateways'].name|[0]" -o tsv)
                echo $appgatewayname
                publicIpAddressId=$(az network application-gateway show --resource-group ${{ env.resourceGroupForWlsAks }} --name ${appgatewayname} --query frontendIpConfigurations[0].publicIpAddress.id -o tsv)
                echo $publicIpAddressId
                appGatewayURL=$(az network public-ip show --resource-group ${{ env.resourceGroupForWlsAks }} --ids ${publicIpAddressId} --query dnsSettings.fqdn -o tsv)
                echo $appGatewayURL
                echo "appGatewayURL=${appGatewayURL}" >> $GITHUB_ENV
            - name: Verify Cargo Tracker is deployed as expected
              run: |
                echo "Verifying Cargo Tracker is deployed as expected"
                curl --verbose http://${{ env.appGatewayURL }}/cargo-tracker/
                response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://${{ env.appGatewayURL }}/cargo-tracker/)
                echo "$response"
                if [ "$response" -ne 200 ]; then
                  echo "Cargo Tracker is not accessible"
                  exit 1
                else
                  echo "Cargo Tracker is accessible"
                fi
            - name: Install kubectl
              if: ${{ github.event.client_payload.isForDemo == 'true' }}
              run: |
                curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
                sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
                kubectl version --client
            - name: Connect to AKS cluster
              if: ${{ github.event.client_payload.isForDemo == 'true' }}
              run: |
                echo "connect to cluster"
                aksClusterName=$(az resource list --resource-group ${{ env.resourceGroupForWlsAks }} --query "[?type=='Microsoft.ContainerService/managedClusters'].name|[0]" -o tsv)
                az aks get-credentials --resource-group ${{ env.resourceGroupForWlsAks }} --name $aksClusterName
            - name: Generate&Apply configmap
              if: ${{ github.event.client_payload.isForDemo == 'true' }}
              run: |
                wlsConfigmapName=sample-domain1-wdt-config-map
                wlsConfigmapJson=cargo-tracker-db.json
                modelFilePath=models
                mkdir ${modelFilePath}
                echo "create configmap"
                echo "export exisiting configmap"
                kubectl -n sample-domain1-ns get configmap ${wlsConfigmapName} -o json >${wlsConfigmapJson}

                echo "query model keys"
                keyList=$(cat ${wlsConfigmapJson} | jq '.data | keys[]' | tr -d "\"")
                for item in $keyList; do
                    data=$(cat ${wlsConfigmapJson} | jq ".data[\"${item}\"]")
                    data=$(echo "${data:1:${#data}-2}")
                    echo -e "${data}" >${modelFilePath}/${item}
                done

                # remove current configmap and create a new one
                kubectl -n sample-domain1-ns delete configmap ${wlsConfigmapName}

                cp cargotracker/src/test/aks/cargo-tracker-jms.yaml ${modelFilePath}/cargo-tracker-jms.yaml

                kubectl -n sample-domain1-ns create configmap ${wlsConfigmapName} \
                --from-file=${modelFilePath}

                kubectl -n sample-domain1-ns label configmap ${wlsConfigmapName} \
                weblogic.domainUID=sample-domain1
                restartVersion=$(kubectl -n sample-domain1-ns get domain sample-domain1 '-o=jsonpath={.spec.restartVersion}')
                # increase restart version
                restartVersion=$((restartVersion + 1))
                echo "append configmap and update restart version"
                kubectl -n sample-domain1-ns patch domain sample-domain1 \
                    --type=json \
                    '-p=[{"op": "replace", "path": "/spec/restartVersion", "value": "'${restartVersion}'" }, {"op": "add", "path": "/spec/configuration/model/configMap", "value": "'${wlsConfigmapName}'" }]'
    cleanup:
      needs: deploy-wls-on-aks
      if: ${{ github.event.client_payload.isForDemo == 'false' }}
      runs-on: ubuntu-latest
      steps:
      - uses: azure/login@v1
        id: azure-login
        with:
          creds: ${{ env.azureCredentials }}
      - name: Delete AKS Resource Group
        id: delete-aks-resource-group
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.azCliVersion }}
          inlineScript: |
            echo "delete... " ${{ env.resourceGroupForWlsAks }}
            az group delete --yes --no-wait --verbose --name ${{ env.resourceGroupForWlsAks }}
